import { buildDecisionEpisodes } from './decision-episodes.js';

const DEFAULT_MIN_SAMPLE=30;

export function compareChampionChallenger(rows=[],challengerRule,{minSample=DEFAULT_MIN_SAMPLE}={}){
  const required=Math.max(10,Number(minSample)||DEFAULT_MIN_SAMPLE),episodeRows=buildDecisionEpisodes(rows),normalized=episodeRows.map(normalize).filter(x=>Number.isFinite(x.forwardReturn));
  const champion=normalized.filter(x=>x.status==='BUY NOW'),challenger=normalized.filter(x=>Boolean(challengerRule?.(x))),championMetrics=metrics(champion),challengerMetrics=metrics(challenger),delta=metricDelta(championMetrics,challengerMetrics),checks={sample:challengerMetrics.sampleSize>=required,expectancy:positiveImprovement(delta.expectancy),marketExcess:positiveImprovement(delta.avgMarketExcessReturn),falsePositiveRate:nonWorse(delta.falsePositiveRate),drawdownProxy:nonWorseNegative(delta.avgMae)};
  const passed=Object.values(checks).filter(Boolean).length,promotable=checks.sample&&checks.expectancy&&checks.marketExcess&&checks.falsePositiveRate&&checks.drawdownProxy;
  return{requiredSample:required,rawObservationSampleSize:(rows||[]).length,decisionEpisodeSampleSize:normalized.length,champion:championMetrics,challenger:challengerMetrics,delta,checks,passedChecks:passed,totalChecks:Object.keys(checks).length,promotable,decision:promotable?'PROMOTION_CANDIDATE':checks.sample?'KEEP_CHAMPION':'COLLECT_MORE_EVIDENCE',policy:'Promotion candidate still requires forward shadow validation; this comparison uses distinct decision episodes and never changes production gates.'};
}

export function buildChallengerRule(config={}){const c={minReadiness:nullable(config.minReadiness),minRvol:nullable(config.minRvol),requireNormalRegime:Boolean(config.requireNormalRegime),requireStrongSector:Boolean(config.requireStrongSector),minGates:nullable(config.minGates),statuses:Array.isArray(config.statuses)&&config.statuses.length?new Set(config.statuses.map(String)):null};return row=>{if(c.statuses&&!c.statuses.has(row.status))return false;if(c.minReadiness!=null&&row.readiness<c.minReadiness)return false;if(c.minRvol!=null&&row.relativeVolume<c.minRvol)return false;if(c.minGates!=null&&row.gatesReady<c.minGates)return false;if(c.requireNormalRegime&&row.riskOff)return false;if(c.requireStrongSector&&!(row.sectorRelativeStrength!=null&&row.sectorRelativeStrength>=0))return false;return true;};}

function metrics(rows){const returns=rows.map(x=>x.forwardReturn),wins=returns.filter(x=>x>0),losses=returns.filter(x=>x<=0),market=rows.map(x=>x.marketExcessReturn).filter(x=>x!=null),mae=rows.map(x=>x.mae).filter(x=>x!=null);return{sampleSize:rows.length,winRate:rate(wins.length,rows.length),expectancy:avg(returns),avgMarketExcessReturn:avg(market),marketBeatRate:rate(market.filter(x=>x>0).length,market.length),falsePositiveRate:rate(losses.length,rows.length),avgMae:avg(mae)};}
function metricDelta(a,b){return{sampleSize:b.sampleSize-a.sampleSize,winRate:diff(b.winRate,a.winRate),expectancy:diff(b.expectancy,a.expectancy),avgMarketExcessReturn:diff(b.avgMarketExcessReturn,a.avgMarketExcessReturn),marketBeatRate:diff(b.marketBeatRate,a.marketBeatRate),falsePositiveRate:diff(b.falsePositiveRate,a.falsePositiveRate),avgMae:diff(b.avgMae,a.avgMae)};}
function normalize(row){let payload=row.payload||{};if(!row.payload&&row.payloadJson){try{payload=JSON.parse(row.payloadJson);}catch{payload={};}}const context=payload.benchmarkContext||{};return{...row,status:String(row.status||''),readiness:finite(row.readiness),relativeVolume:finite(row.relativeVolume),gatesReady:Number(row.gatesReady)||0,riskOff:Boolean(Number(row.benchmarkRiskOff??payload.benchmarkRiskOff)),sectorRelativeStrength:nullable(context.sectorRelativeStrength20),forwardReturn:numberOrNaN(row.forwardReturn),marketExcessReturn:nullable(row.marketExcessReturn),mae:nullable(row.mae)};}
function positiveImprovement(v){return v!=null&&v>0;}function nonWorse(v){return v!=null&&v<=0;}function nonWorseNegative(v){return v!=null&&v>=0;}function diff(a,b){return a==null||b==null?null:a-b;}function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null;}function rate(n,d){return d?n/d:null;}function finite(v){const n=Number(v);return Number.isFinite(n)?n:0;}function numberOrNaN(v){const n=Number(v);return Number.isFinite(n)?n:Number.NaN;}function nullable(v){const n=Number(v);return v!==null&&v!==undefined&&Number.isFinite(n)?n:null;}
