import { broadDiscoveryCoverage } from './scanner-schedule.js';
import { MIN_BUY_REWARD_RISK } from './hard-guardrails.js';

export const DETECTION_LATENCY_THRESHOLDS=Object.freeze({
  firstScanAlreadyMovedPct:1.0,
  radarMeaningfulMovePct:1.0,
  promotionMinutes:30,
  promotionPriceAdvancePct:.75,
  readyMinutes:45,
  readyPriceAdvancePct:1.0,
  readyObservedMoveConsumedRate:.60,
  rewardRiskMin:MIN_BUY_REWARD_RISK,
  peakWindowMs:2*24*60*60*1000
});

const MOVEMENT_STATES=new Set(['MOVEMENT WATCH','EARLY MOVEMENT — BUILDING']);

export async function getDetectionLatencyAudit(env,{symbol,lookbackDays=3,now=Date.now()}={}){
  const clean=sanitizeSymbol(symbol);if(!clean)return{error:'Invalid symbol.'};
  const days=Math.max(1,Math.min(30,Number(lookbackDays)||3)),since=Number(now)-days*86_400_000;
  const result=await env.DB.prepare(`SELECT id,symbol,observation_type AS observationType,source,observed_at AS observedAt,price,change_pct AS changePct,status,readiness,rr,gates_ready AS gatesReady,gate_total AS gateTotal,trend_ready AS trendReady,entry_ready AS entryReady,probability_ready AS probabilityReady,risk_reward_ready AS riskRewardReady,preferred_entry_low AS preferredEntryLow,preferred_entry_high AS preferredEntryHigh,payload_json AS payloadJson FROM evidence_observations WHERE symbol=? AND observed_at>=? AND observation_type IN ('RADAR','ANALYSIS') ORDER BY observed_at ASC,id ASC`).bind(clean,since).all();
  return evaluateDetectionLatencyRows(result.results||[],{symbol:clean,lookbackDays:days,now});
}

export function evaluateDetectionLatencyRows(rows=[],{symbol='',lookbackDays=3,now=Date.now()}={}){
  const normalized=(rows||[]).map(normalizeRow).filter(row=>row.symbol&&Number.isFinite(row.observedAt)).sort((a,b)=>a.observedAt-b.observedAt||a.id-b.id);
  const cleanSymbol=String(symbol||normalized[0]?.symbol||'').toUpperCase(),radar=normalized.filter(row=>row.observationType==='RADAR'),analysis=normalized.filter(row=>row.observationType==='ANALYSIS');
  const firstRadar=radar[0]||null,firstMovement=radar.find(row=>MOVEMENT_STATES.has(row.status))||null,firstBuilding=radar.find(row=>row.status==='EARLY MOVEMENT — BUILDING')||null,firstAnalysis=analysis[0]||null,firstReady=analysis.find(row=>row.status==='SETUP — READY SOON')||null,firstBuy=analysis.find(row=>row.status==='BUY NOW')||null,latestAnalysis=analysis.at(-1)||null;
  const anchor=firstMovement||firstRadar||firstAnalysis||normalized[0]||null,peak=maxPrice(normalized.filter(row=>anchor&&row.observedAt>=anchor.observedAt&&row.observedAt<=anchor.observedAt+DETECTION_LATENCY_THRESHOLDS.peakWindowMs));
  const buyEligibleWithoutBuy=analysis.find(row=>row.status!=='BUY NOW'&&looksBuyEligible(row))||null,closest=closestToBuy(analysis);
  const latency={
    firstRadarToMovementMinutes:minutesBetween(firstRadar,firstMovement),movementToAnalysisMinutes:minutesBetween(firstMovement,firstAnalysis),movementToReadyMinutes:minutesBetween(firstMovement,firstReady),movementToBuyMinutes:minutesBetween(firstMovement,firstBuy),
    priceAdvanceMovementToAnalysisPct:priceChange(firstMovement,firstAnalysis),priceAdvanceMovementToReadyPct:priceChange(firstMovement,firstReady),priceAdvanceMovementToBuyPct:priceChange(firstMovement,firstBuy),observedUpswingPct:priceChange(anchor,peak),observedMoveConsumedBeforeReadyRate:moveConsumed(anchor,firstReady,peak)
  };
  const scannerHealth=radarHealth(radar),findings=[];
  if(!normalized.length)findings.push(finding('NO_STORED_EVIDENCE','INFO','No stored radar or scheduled analysis evidence exists in this audit window.'));
  if(firstRadar&&finite(firstRadar.changePct)>=DETECTION_LATENCY_THRESHOLDS.firstScanAlreadyMovedPct)findings.push(finding('FIRST_SCAN_AFTER_MOVE','WARN',`The first stored radar observation already showed ${pct(firstRadar.changePct)} versus the prior close, so part of the move may have happened before SignalForge first sampled it.`));
  const maxRadarMove=Math.max(0,...radar.map(row=>finite(row.changePct)));
  if(radar.length&&!firstMovement&&maxRadarMove>=DETECTION_LATENCY_THRESHOLDS.radarMeaningfulMovePct)findings.push(finding('MOVEMENT_TRIGGER_MISSED','CRITICAL',`Radar observed as much as ${pct(maxRadarMove)} versus the prior close but never promoted the row above QUIET.`));
  if(firstMovement&&!firstAnalysis)findings.push(finding('NOT_PROMOTED','CRITICAL','Early movement was stored, but no scheduled deep-analysis evidence followed in the audit window.'));
  if(firstMovement&&firstAnalysis&&(finite(latency.movementToAnalysisMinutes)>DETECTION_LATENCY_THRESHOLDS.promotionMinutes||finite(latency.priceAdvanceMovementToAnalysisPct)>DETECTION_LATENCY_THRESHOLDS.promotionPriceAdvancePct))findings.push(finding('PROMOTION_LATE','WARN',`Deep analysis began ${fmtMinutes(latency.movementToAnalysisMinutes)} after the first movement signal, after a ${pct(latency.priceAdvanceMovementToAnalysisPct)} price advance.`));
  if(firstMovement&&firstReady&&(finite(latency.movementToReadyMinutes)>DETECTION_LATENCY_THRESHOLDS.readyMinutes||finite(latency.priceAdvanceMovementToReadyPct)>DETECTION_LATENCY_THRESHOLDS.readyPriceAdvancePct||(latency.observedMoveConsumedBeforeReadyRate!=null&&latency.observedMoveConsumedBeforeReadyRate>=DETECTION_LATENCY_THRESHOLDS.readyObservedMoveConsumedRate)))findings.push(finding('READY_LATE','WARN',`READY arrived ${fmtMinutes(latency.movementToReadyMinutes)} after first movement; price had advanced ${pct(latency.priceAdvanceMovementToReadyPct)} from that stored movement observation.`));
  if(buyEligibleWithoutBuy)findings.push(finding('POSSIBLE_DECISION_INCONSISTENCY','CRITICAL',`A stored analysis snapshot appears to have all four critical gates, participation, and ${MIN_BUY_REWARD_RISK.toFixed(2)}:1+ R/R while its status was not BUY NOW. Review this snapshot as a possible engine inconsistency.`));
  if(!firstBuy&&latestAnalysis&&latestAnalysis.rr!=null&&latestAnalysis.rr<DETECTION_LATENCY_THRESHOLDS.rewardRiskMin)findings.push(finding('CURRENT_RR_BLOCK','INFO',`Current stored R/R is ${round(latestAnalysis.rr,2)}:1, below the unchanged ${DETECTION_LATENCY_THRESHOLDS.rewardRiskMin.toFixed(2)}:1 BUY requirement.`));
  if(!firstBuy&&closest)findings.push(finding('BUY_NEVER_CONFIRMED','INFO',describeClosestBlock(closest)));
  const detection=assessDetection({normalized,radar,firstRadar,firstMovement,firstAnalysis,firstReady,latency,maxRadarMove}),execution=assessExecution({firstBuy,buyEligibleWithoutBuy,latestAnalysis,closest});
  return{symbol:cleanSymbol,lookbackDays:Number(lookbackDays)||3,generatedAt:Number(now)||Date.now(),observationCount:normalized.length,radarObservationCount:radar.length,analysisObservationCount:analysis.length,milestones:{firstRadar:milestone(firstRadar),firstMovement:milestone(firstMovement),firstBuilding:milestone(firstBuilding),firstAnalysis:milestone(firstAnalysis),firstReady:milestone(firstReady),firstBuy:milestone(firstBuy),closestToBuy:milestone(closest),latestAnalysis:milestone(latestAnalysis),maxObservedEvidencePrice:milestone(peak)},latency,scannerHealth,coverage:broadDiscoveryCoverage(),assessment:{detection,execution,likelyMissedEarlyOpportunity:['POSSIBLY_LATE_BEFORE_FIRST_SCAN','MOVEMENT_TRIGGER_MISSED','PROMOTION_LATE','READY_LATE','NOT_PROMOTED'].includes(detection.code),validBuyMissed:buyEligibleWithoutBuy?'POSSIBLE_ENGINE_INCONSISTENCY':firstBuy?false:null,policy:'Price movement alone never proves a valid BUY was missed. A missed valid BUY is only flagged when stored critical gates, participation, and reward/risk appear BUY-eligible without a BUY NOW status.'},findings,thresholds:{...DETECTION_LATENCY_THRESHOLDS},dataPolicy:{providerRequests:0,source:'stored evidence_observations only',note:'This audit does not request fresh market data. It can measure latency after SignalForge stored an observation, but cannot reconstruct price action the scanner never sampled.'}};
}

function assessDetection({normalized,radar,firstRadar,firstMovement,firstAnalysis,firstReady,latency,maxRadarMove}){if(!normalized.length)return{code:'NO_HISTORY',label:'NO HISTORY',severity:'INFO',reason:'No stored evidence exists in the audit window.'};if(!radar.length)return{code:'NO_RADAR_HISTORY',label:'NO RADAR HISTORY',severity:'WARN',reason:'Analysis exists without recent stored radar observations, so discovery latency cannot be measured.'};if(!firstMovement&&maxRadarMove>=DETECTION_LATENCY_THRESHOLDS.radarMeaningfulMovePct)return{code:'MOVEMENT_TRIGGER_MISSED',label:'MOVEMENT TRIGGER MISSED',severity:'CRITICAL',reason:'Radar saw a meaningful daily move but the early-movement state remained QUIET.'};if(firstRadar&&finite(firstRadar.changePct)>=DETECTION_LATENCY_THRESHOLDS.firstScanAlreadyMovedPct)return{code:'POSSIBLY_LATE_BEFORE_FIRST_SCAN',label:'MOVE ALREADY UNDERWAY',severity:'WARN',reason:`The first stored radar sample was already ${pct(firstRadar.changePct)} from the prior close.`};if(firstMovement&&!firstAnalysis)return{code:'NOT_PROMOTED',label:'NOT PROMOTED',severity:'CRITICAL',reason:'Movement was detected but no deep-analysis evidence followed.'};if(firstMovement&&firstAnalysis&&(finite(latency.movementToAnalysisMinutes)>DETECTION_LATENCY_THRESHOLDS.promotionMinutes||finite(latency.priceAdvanceMovementToAnalysisPct)>DETECTION_LATENCY_THRESHOLDS.promotionPriceAdvancePct))return{code:'PROMOTION_LATE',label:'PROMOTION LATE',severity:'WARN',reason:'SignalForge detected movement, but higher-cost analysis arrived late.'};if(firstMovement&&firstReady&&(finite(latency.movementToReadyMinutes)>DETECTION_LATENCY_THRESHOLDS.readyMinutes||finite(latency.priceAdvanceMovementToReadyPct)>DETECTION_LATENCY_THRESHOLDS.readyPriceAdvancePct||(latency.observedMoveConsumedBeforeReadyRate!=null&&latency.observedMoveConsumedBeforeReadyRate>=DETECTION_LATENCY_THRESHOLDS.readyObservedMoveConsumedRate)))return{code:'READY_LATE',label:'READY LATE',severity:'WARN',reason:'The setup reached READY only after substantial elapsed time or price movement.'};if(firstMovement)return{code:'TIMELY_AFTER_RADAR',label:'TIMELY AFTER RADAR',severity:'OK',reason:'Stored promotion/READY timing did not cross the Stage 14.28 late-detection thresholds.'};return{code:'NO_EARLY_TRIGGER',label:'NO EARLY TRIGGER',severity:'INFO',reason:'Recent radar history never reached MOVEMENT WATCH or EARLY MOVEMENT — BUILDING.'};}
function assessExecution({firstBuy,buyEligibleWithoutBuy,latestAnalysis,closest}){if(firstBuy)return{code:'BUY_CONFIRMED',label:'BUY WAS CONFIRMED',severity:'OK',reason:`BUY NOW was stored at ${money(firstBuy.price)}.`};if(buyEligibleWithoutBuy)return{code:'POSSIBLE_MISSED_VALID_BUY',label:'REVIEW POSSIBLE MISSED BUY',severity:'CRITICAL',reason:'A non-BUY snapshot appears BUY-eligible from the stored critical gates, participation, and R/R.'};if(latestAnalysis?.rr!=null&&latestAnalysis.rr<DETECTION_LATENCY_THRESHOLDS.rewardRiskMin)return{code:'NO_BUY_RR_BLOCKED',label:'NO VALID BUY — R/R BLOCKED',severity:'OK',reason:`Latest stored R/R ${round(latestAnalysis.rr,2)}:1 is below ${DETECTION_LATENCY_THRESHOLDS.rewardRiskMin.toFixed(2)}:1.`};if(closest)return{code:'NO_BUY_CONFIRMED',label:'NO VALID BUY CONFIRMED',severity:'INFO',reason:describeClosestBlock(closest)};return{code:'NO_ANALYSIS',label:'NO ANALYSIS',severity:'INFO',reason:'No stored deep-analysis snapshot exists in the audit window.'};}
function describeClosestBlock(row){const blockers=[];if(row.gatesReady<row.gateTotal)blockers.push(`${Math.max(0,row.gateTotal-row.gatesReady)} critical gate(s)`);if(row.participationPass===false)blockers.push('participation');if(row.rr!=null&&row.rr<DETECTION_LATENCY_THRESHOLDS.rewardRiskMin)blockers.push(`R/R ${round(row.rr,2)}:1`);for(const x of row.criticalFailed.slice(0,3))if(!blockers.includes(x))blockers.push(x);return blockers.length?`Closest stored setup still failed: ${blockers.join(', ')}.`:'No BUY NOW was stored; the saved evidence does not prove a valid BUY was missed.';}
function looksBuyEligible(row){return row.gateTotal>0&&row.gatesReady>=row.gateTotal&&row.trendReady===true&&row.entryReady===true&&row.probabilityReady===true&&row.riskRewardReady===true&&row.participationPass===true&&row.rr!=null&&row.rr>=DETECTION_LATENCY_THRESHOLDS.rewardRiskMin;}
function closestToBuy(rows){return(rows||[]).slice().sort((a,b)=>buyScore(b)-buyScore(a)||a.observedAt-b.observedAt)[0]||null;}function buyScore(row){return finite(row.gatesReady)*100+(row.participationPass?70:0)+(row.rr!=null&&row.rr>=DETECTION_LATENCY_THRESHOLDS.rewardRiskMin?50:0)+finite(row.readiness);}
function radarHealth(rows){const gaps=[];for(let i=1;i<rows.length;i++){const gap=(rows[i].observedAt-rows[i-1].observedAt)/60000;if(Number.isFinite(gap)&&gap>=0)gaps.push(gap);}const sorted=gaps.slice().sort((a,b)=>a-b);return{observations:rows.length,medianGapMinutes:sorted.length?round(sorted[Math.floor(sorted.length/2)],1):null,maxGapMinutes:sorted.length?round(Math.max(...sorted),1):null,firstObservedAt:rows[0]?.observedAt||null,lastObservedAt:rows.at(-1)?.observedAt||null};}
function milestone(row){if(!row)return null;return{at:row.observedAt,price:row.price,changePct:row.changePct,status:row.status,source:row.source,readiness:row.readiness,rr:row.rr,gatesReady:row.gatesReady,gateTotal:row.gateTotal,participationPass:row.participationPass,criticalFailed:row.criticalFailed,preferredEntryLow:row.preferredEntryLow,preferredEntryHigh:row.preferredEntryHigh};}
function normalizeRow(row){const payload=parseJson(row?.payload??row?.payloadJson),participation=payload?.participation||null;return{id:Number(row?.id)||0,symbol:String(row?.symbol||'').toUpperCase(),observationType:String((row?.observationType??row?.observation_type)||''),source:String(row?.source||''),observedAt:numberOrNaN(row?.observedAt??row?.observed_at),price:nullable(row?.price),changePct:nullable(row?.changePct??row?.change_pct),status:String(row?.status||''),readiness:nullable(row?.readiness),rr:nullable(row?.rr),gatesReady:Number(row?.gatesReady??row?.gates_ready)||0,gateTotal:Number(row?.gateTotal??row?.gate_total)||4,trendReady:boolOrNull(row?.trendReady??row?.trend_ready),entryReady:boolOrNull(row?.entryReady??row?.entry_ready),probabilityReady:boolOrNull(row?.probabilityReady??row?.probability_ready),riskRewardReady:boolOrNull(row?.riskRewardReady??row?.risk_reward_ready),preferredEntryLow:nullable(row?.preferredEntryLow??row?.preferred_entry_low),preferredEntryHigh:nullable(row?.preferredEntryHigh??row?.preferred_entry_high),participationPass:participation?Boolean(participation.pass&&participation.participationPass):null,criticalFailed:Array.isArray(payload?.criticalFailed)?payload.criticalFailed.map(String):[],payload};}
function maxPrice(rows){return(rows||[]).filter(row=>row.price!=null).sort((a,b)=>b.price-a.price||a.observedAt-b.observedAt)[0]||null;}function minutesBetween(a,b){return a&&b&&b.observedAt>=a.observedAt?round((b.observedAt-a.observedAt)/60000,1):null;}function priceChange(a,b){return a?.price>0&&b?.price!=null?round((b.price/a.price-1)*100,2):null;}function moveConsumed(start,ready,peak){if(!(start?.price>0)||ready?.price==null||!(peak?.price>start.price))return null;return round(Math.max(0,Math.min(1,(ready.price-start.price)/(peak.price-start.price))),3);}function finding(code,severity,message){return{code,severity,message};}
function parseJson(value){if(value&&typeof value==='object')return value;try{return JSON.parse(value||'{}');}catch{return{};}}function boolOrNull(v){if(v===null||v===undefined)return null;return Boolean(Number(v)||v===true);}function nullable(v){const n=Number(v);return v!==null&&v!==undefined&&Number.isFinite(n)?n:null;}function numberOrNaN(v){const n=Number(v);return Number.isFinite(n)?n:Number.NaN;}function finite(v){const n=Number(v);return Number.isFinite(n)?n:0;}function round(v,d=2){const n=Number(v);if(!Number.isFinite(n))return null;const p=10**d;return Math.round(n*p)/p;}function pct(v){return v==null?'n/a':`${round(v,2).toFixed(2)}%`;}function fmtMinutes(v){return v==null?'an unknown interval':`${round(v,1)} min`;}function money(v){return v==null?'an unknown price':`$${round(v,2).toFixed(2)}`;}function sanitizeSymbol(v){const s=String(v||'').trim().toUpperCase();return/^[A-Z]{1,5}(?:\.[A-Z])?$/.test(s)?s:'';}
