import { ensureOutcomeSchema } from './outcomes.js';
import { analyzeDecisionErrors, buildSetupLeaderboard, compareGateValue } from './strategy-optimizer.js';
import { buildChallengerRule, compareChampionChallenger } from './challenger.js';
import { getShadowValidationReport } from './shadow-validation.js';
import { buildDecisionEpisodes } from './decision-episodes.js';

export async function getOptimizationReport(env,{horizon=10,minSample=20,winnerThreshold=.05,challenger={}}={}){
  await ensureOutcomeSchema(env);
  const h=normalizeHorizon(horizon),required=Math.max(5,Number(minSample)||20),threshold=clamp(Number(winnerThreshold),.01,.25,.05);
  const result=await env.DB.prepare(`SELECT e.id,e.symbol,e.source,e.status,e.readiness,e.relative_volume AS relativeVolume,e.gates_ready AS gatesReady,e.gate_total AS gateTotal,e.benchmark_risk_off AS benchmarkRiskOff,e.model_version AS modelVersion,e.observed_at AS observedAt,e.payload_json AS payloadJson,o.forward_return AS forwardReturn,o.mfe,o.mae,o.market_excess_return AS marketExcessReturn,o.sector_excess_return AS sectorExcessReturn FROM evidence_observations e JOIN evidence_outcomes o ON o.observation_id=e.id WHERE e.observation_type='ANALYSIS' AND o.horizon_sessions=? ORDER BY e.observed_at ASC,e.id ASC`).bind(h).all();
  const rows=result.results||[],episodes=buildDecisionEpisodes(rows),leaderboard=buildSetupLeaderboard(rows,{minSample:required}),errors=analyzeDecisionErrors(rows,{winnerThreshold:threshold}),gates=compareGateValue(rows),challengerConfig=normalizeChallenger(challenger),championVsChallenger=compareChampionChallenger(rows,buildChallengerRule(challengerConfig),{minSample:Math.max(10,required)}),shadow=await getShadowValidationReport(env,{refresh:true});
  return{horizon:h,minSample:required,winnerThreshold:threshold,sampleSize:episodes.length,rawObservationSampleSize:rows.length,generatedAt:Date.now(),leaderboard,qualifiedSetups:leaderboard.filter(x=>x.qualified),decisionErrors:errors,gateValue:gates,challenger:{config:challengerConfig,...championVsChallenger},shadowValidation:shadow,recommendations:recommendations({leaderboard,gates,errors,required,championVsChallenger,shadow}),policy:{liveGateChanges:false,mode:'EVIDENCE_ONLY',message:'Optimization findings are advisory and are now sampled by distinct decision episodes. Production rules remain unchanged until a challenger clears retrospective checks and then independently passes forward shadow validation.'}};
}

function recommendations({leaderboard,gates,errors,required,championVsChallenger,shadow}){
  const out=[],best=leaderboard.find(x=>x.qualified);if(best)out.push({type:'SETUP_LEADER',confidence:'QUALIFIED',message:`Best qualified setup is ${best.key} with ${(100*(best.winRate||0)).toFixed(1)}% win rate and ${pct(best.expectancy)} expectancy across ${best.sampleSize} decision episodes.`});
  if(championVsChallenger.promotable)out.push({type:'CHALLENGER_CANDIDATE',confidence:'SHADOW_ONLY',message:'The configured challenger clears retrospective episode-based promotion checks. Production remains unchanged while forward shadow validation collects post-rollout evidence.'});
  const forwardPass=(shadow?.challengers||[]).find(x=>x.status==='FORWARD_PASS');if(forwardPass)out.push({type:'FORWARD_SHADOW_PASS',confidence:'REVIEW_REQUIRED',message:`${forwardPass.name} passed forward shadow validation across ${forwardPass.evaluation?.challenger?.sampleSize||0} challenger decision episodes. This nominates it for deliberate review; production is still unchanged.`});
  const weakGate=gates.filter(x=>x.fail.sampleSize>=required&&x.winnerBlockRate!=null).sort((a,b)=>finite(b.winnerBlockRate)-finite(a.winnerBlockRate))[0];if(weakGate&&weakGate.winnerBlockRate>=.55)out.push({type:'GATE_REVIEW',confidence:'RESEARCH',message:`${weakGate.gate} blocked winners in ${(weakGate.winnerBlockRate*100).toFixed(1)}% of its failed decision episodes; test it in a challenger before changing production.`});
  const fp=errors.falsePositives?.topCharacteristics?.[0];if(fp)out.push({type:'FALSE_POSITIVE_PATTERN',confidence:'RESEARCH',message:`Most common losing-BUY characteristic: ${fp.key} (${fp.count}/${errors.falsePositives.sampleSize} decision episodes).`});
  const mw=errors.missedWinners?.topCharacteristics?.[0];if(mw)out.push({type:'MISSED_WINNER_PATTERN',confidence:'RESEARCH',message:`Most common missed-winner characteristic: ${mw.key} (${mw.count}/${errors.missedWinners.sampleSize} decision episodes).`});
  if(!best)out.push({type:'INSUFFICIENT_SAMPLE',confidence:'WAIT',message:`No setup cohort has reached the ${required}-episode qualification threshold yet.`});return out;
}
function normalizeChallenger(c={}){return{statuses:Array.isArray(c.statuses)&&c.statuses.length?c.statuses:['BUY NOW'],minReadiness:bounded(c.minReadiness,0,100,80),minRvol:bounded(c.minRvol,0,10,1.5),minGates:bounded(c.minGates,0,4,4),requireNormalRegime:c.requireNormalRegime!==false,requireStrongSector:c.requireStrongSector!==false};}
function bounded(v,min,max,fallback){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;}function normalizeHorizon(v){const n=Number(v);return[1,3,5,10,20].includes(n)?n:10;}function clamp(v,min,max,fallback){return Number.isFinite(v)?Math.min(max,Math.max(min,v)):fallback;}function finite(v){const n=Number(v);return Number.isFinite(n)?n:0;}function pct(v){return v==null?'n/a':`${(Number(v)*100).toFixed(2)}%`;}
